bugfix add/remove, rename commands and add minimal autocompletion

diff --git a/bin/gitsy b/bin/gitsy
--- a/bin/gitsy
+++ b/bin/gitsy
@@ -1,12 +1,14 @@
 #!/bin/bash
-   GITSY_VERSION=0.4
-  GITSY_HOOKNAME=${1:-''}; shift
+   GITSY_VERSION=0.5
+   GITSY_COMMAND=${1:-''}; shift
     GITSY_PARAMS="$@"
         GITSY_WK="$(pwd)"
     GITSY_ORIGIN="origin"
     GITSY_UPSYNC="upsync"
+     GITSY_ALIAS="spush"
    GITSY_NOCOLOR=0
  GITSY_PULLFIRST=0
+     GITSY_QUIET=0
     GITSY_SCRIPT=$0
 GITSY_TERM_WIDTH=105
 
@@ -21,10 +23,13 @@ if [ "$GITSY_NOCOLOR" -eq 0 ]; then
             Cval="\033[1;38;5;215m"
             Cusa="\033[1;38;5;214m"
             Cbra="\033[1;38;5;203m"
+           Crepo="\033[1;38;5;223m"
+           Cmeta="\033[1;38;5;36m"
            Ctext="\033[1;38;5;30m"
             Copt="\033[1;38;5;84m"
             Csep="\033[1;38;5;241m"
             Cerr="\033[1;38;5;196m"
+            Ccom="\033[0;38;5;139m"
 fi
 
 # -------------------------------------------------------
@@ -70,7 +75,7 @@ function gitsy.echo.state(){
 }
 # -------------------------------------------------------
 function gitsy.echo.error(){
-    echo -e "${Cerr}    error : ${Coff} $1 ${Coff}\n"
+    echo -e "\n${Cerr}    error : ${Coff}\n\t$1 ${Coff}\n"
 }
 # -------------------------------------------------------
 function gitsy.sepline(){
@@ -91,7 +96,7 @@ function gitsy.title(){
     gitsy.sepline
     echo -ne " $Ctsep :: $Ctitle$msg $Ctsep:: $Coff"
     printf "%0.s " $(seq 1 $(($GITSY_TERM_WIDTH-${#len}-15)))
-    echo -e " ${Cok}author : ${Cval}a-Sansara"
+    echo -e " ${Cmeta}author : ${Cval}a-Sansara"
     gitsy.sepline
 }
 # -------------------------------------------------------
@@ -125,8 +130,7 @@ function gitsy.upstream.track(){
 function gitsy.mktemp(){
     tfile="$(mktemp)"
     if [ ! -f "$tfile" ]; then
-        gitsy.echo.error "\n
-        can't make temp file"
+        gitsy.echo.error "can't make temp file"
         exit 1
     fi
 }
@@ -158,8 +162,16 @@ function gitsy.match.remote(){
 }
 # -------------------------------------------------------
 function gitsy.remove.infile(){
-    gitsy.mktemp
-    grep -v "$1" "$2" > "$tfile" && mv "$tfile" "$2"
+    local repo=''
+    local data=''
+    if [ -f ".gitsy" ]; then
+        while read repo; do
+            if [ ! "$1" = "$repo" ]; then
+                data="$repo\n"
+            fi
+        done < .gitsy
+    fi
+    echo -e "$data" > "$2"
 }
 # -------------------------------------------------------
 function gisty.sync.list(){
@@ -197,8 +209,7 @@ function gitsy.spush(){
     if [ "$rs" = 0 ]; then
         gitsy.echo.state 0
         echo
-        gitsy.echo.action "looking for upsync repositories"
-        gisty.sync.list
+        gisty.list
         echo
         for name in $(git remote -v | grep ^${GITSY_UPSYNC}[^\(]*\(push\)$ | cut -f 1); do
             gitsy.echo.action "pushing on ${Copt}$opt ${Cspe}$name ${Cbra}$branch"
@@ -221,24 +232,37 @@ function gitsy.spush(){
     fi
 }
 # -------------------------------------------------------
-function gitsy.disync(){
+function gitsy.remove(){
     local repo=${1:-''}
     if [ ! -z "$repo" ]; then
         if [ ! "${repo:0:${#GITSY_UPSYNC}}" = "$GITSY_UPSYNC" ]; then
             repo="$GITSY_UPSYNC-$repo"
         fi
+        echo $repo
         gitsy.remove.infile "$repo" ".gitsy"
         echo
-        gitsy.echo.action "synchro list : "
-        gisty.sync.list
+        gitsy.list
     else
-        gitsy.error "\n
-        you must specified a repository !"
+        gitsy.error "you must specified a repository !"
     fi
 }
 
 # -------------------------------------------------------
-function gitsy.upsync(){
+function gitsy.list(){
+    local name active
+    gitsy.echo.action "listing upsync repositories : "
+    for name in $(git remote -v | grep ^${GITSY_UPSYNC}[^\(]*\(push\)$ | cut -f 1); do
+        gitsy.match.infile "$name" ".gitsy"        
+        active="${Cbra}disabled"
+        if gitsy.match.infile "$name" ".gitsy"; then
+            active="${Copt}active"
+        fi
+        name=$(printf "%-30s" "$name")
+        gitsy.echo "${Cspe}$name ${Copt}$active" 1 "     -"
+    done
+}
+# -------------------------------------------------------
+function gitsy.add(){
     if [ -d ./.git ]; then
         local repo=${1:-''}
         local  url=${2:-''}
@@ -258,25 +282,23 @@ function gitsy.upsync(){
                 gitsy.echo "     git remote already exists"
             else
                 if [ -z "$url" ]; then
-                    gitsy.error "\n
-        you must specified a remote url !"
+                    gitsy.remove.infile "$repo" ".gitsy"
+                    gitsy.error "you must specified a remote url !"
                 else
                     gitsy.echo.action "git adding remote ${Cspe}$repo ${Cbra}$url"
                     git remote add "$repo" "$url"
                 fi
             fi
             echo
-            gitsy.echo.action "synchro list : "
-            gisty.sync.list
+            gitsy.list
             echo -e "
       You can now use :
-      ${Cspe}git spush ${Copt}repository ${Cbra}branch${Coff}
+      ${Cspe}git $GITSY_ALIAS ${Copt}repository ${Cbra}branch${Coff}
       Or :
-      ${Cspe}gitsy spush ${Copt}repository ${Cbra}branch${Coff}
+      ${Cspe}gitsy $GITSY_ALIAS ${Copt}repository ${Cbra}branch${Coff}
 "
         else
-            gitsy.error "\n
-        you must specified a REPOSITORY !"
+            gitsy.error "you must specified a REPOSITORY !"
         fi
     fi
 }
@@ -308,12 +330,11 @@ function gitsy.help(){
 }
 # -------------------------------------------------------
 function gitsy.check.command(){
-    case "$GITSY_HOOKNAME" in
-        'spush'|'upsync'|'disync')
+    case "$GITSY_COMMAND" in
+        '$GITSY_ALIAS'|'add'|'remove')
             if [ -z "$(git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/')" ]; then
-                gitsy.error "\n
-            ${Cval}$(pwd)${Coff} is not a git repository. 
-            you must chdir to a repository before using ${Cval}$GITSY_HOOKNAME" 1
+                gitsy.error "${Cval}$(pwd)${Coff} is not a git repository. 
+    you must chdir to a repository before using ${Cval}$GITSY_COMMAND" 1
             fi
     esac
 }
@@ -332,6 +353,16 @@ function gitsy.parse.install.args(){
     if [ "$opt" = "-f" ] || [ "$opt" = "--force" ]; then
         force="true"
     fi
+}
+# -------------------------------------------------------
+function gitsy.uninstall(){
+    gitsy.echo.action "Uninstalling ${Cbra}gitsy"
+    rm -f $GITSY_SCRIPT 2> /dev/null
+    local rs="$?"
+    if [ "$rs" = "1" ]; then
+        gitsy.error "permission denied" 0
+    fi
+    gitsy.echo.state "$rs"
 }
 # -------------------------------------------------------
 function gitsy.install(){
@@ -360,86 +391,92 @@ gitsy.main
 " > "$dir/gitsy"
                     gitsy.on.install "$force" "$(logname)"
                 else
-                    gitsy.echo.error "\n
-        permission denied"
+                    gitsy.echo.error "permission denied"
                     gitsy.echo.state 1
                     exit 1
                 fi
             fi
         else
-            gitsy.echo.error "\n
-        directory ${Cspe}'$dir'${Coff} does not exists"
+            gitsy.echo.error "directory ${Cspe}'$dir'${Coff} does not exists"
             exit 1
         fi
     fi
 }
 # -------------------------------------------------------
 function gitsy.on.install(){
-    local spush="$(git config --list | grep alias.spush)"
+    local spush="$(git config --list | grep alias.$GITSY_ALIAS)"
     if [ ! -z "$spush" ]; then
-        if [ "$spush" = "alias.spush=!bash gitsy spush" ]; then
-            gitsy.echo "     git alias spush already exists. skip"
+        if [ "$spush" = "alias.$GITSY_ALIAS=!bash gitsy $GITSY_ALIAS" ]; then
+            gitsy.echo "     git alias $GITSY_ALIAS already exists. skip"
         elif [ "$1" = "true" ]; then
-            gitsy.echo.action "rewriting git alias ${Cspe}spush"
-            su -c "git config --global --unset alias.spush" $2
-            su -c "git config --global alias.spush '!bash gitsy spush'" $2
+            gitsy.echo.action "rewriting git alias ${Cspe}$GITSY_ALIAS"
+            su -c "git config --global --unset alias.$GITSY_ALIAS" $2
+            su -c "git config --global alias.$GITSY_ALIAS '!bash gitsy $GITSY_ALIAS'" $2
             
         else
-            gitsy.error "\n
-        git alias.spush exists in ~/.gitconfig but has a wrong definition. remove it or rename it" 0
+            gitsy.error "git alias.$GITSY_ALIAS exists in ~/.gitconfig but has a wrong definition. remove it or rename it" 0
         fi
     else
-        gitsy.echo.action "enabling git alias ${Cspe}spush ${Cok}for user ${Cbra}$2"
-        su -c "git config --global alias.spush '!bash gitsy spush'" $2
+        gitsy.echo.action "enabling git alias ${Cspe}$GITSY_ALIAS ${Cok}for user ${Cbra}$2"
+        su -c "git config --global alias.$GITSY_ALIAS '!bash gitsy $GITSY_ALIAS'" $2
     fi
     gitsy.echo.state 0
 }
 # -------------------------------------------------------
 function gitsy.usage(){
-    echo -e "    ${Cusa}usage :${Coff}
-
-    ${Cspe}\tgitsy  ${Copt}spush      ${Ctext}REPOSITORY BRANCH
-    ${Cspe}\tgitsy  ${Copt}upsync     ${Ctext}REPOSITORY ${Copt}[ ${Ctext}URL${Copt} ]
-    ${Cspe}\tgitsy  ${Copt}disync     ${Ctext}REPOSITORY"
+    echo -e "    ${Cusa}Global Options :${Coff}\n
+    ${Ctext}\t-h, --help        ${Ccom}display help
+    ${Ctext}\t-v, --version     ${Ccom}display program version
+    ${Ctext}\t-q, --quiet       ${Ccom}quiet output\n
+    ${Cusa}Usage :${Coff}\n
+    ${Ccom}\tlist the upsync repositories in current project
+    ${Cspe}\tgitsy  ${Copt}list
+    ${Ccom}\texecute synchronized push in current project
+    ${Cspe}\tgitsy  ${Copt}$GITSY_ALIAS      ${Copt}[ ${Ctext}-f, --force${Copt} ] ${Ctext}REPOSITORY BRANCH
+    ${Ccom}\tadd an upsync repository to current project ('upsync-' prefix is optionnal)
+    ${Cspe}\tgitsy  ${Copt}add        ${Ctext}REPOSITORY ${Copt}[ ${Ctext}URL${Copt} ]
+    ${Ccom}\tremove an upsync repository to current project ('upsync-' prefix is optionnal)
+    ${Ccom}\tuse -g option to remove from git current project configuration file
+    ${Cspe}\tgitsy  ${Copt}remove     ${Copt}[ ${Ctext}-g, --git${Copt} ] ${Ctext}REPOSITORY"
     if [ ! "$GITSY_INSTALLED" = "true" ]; then
+        echo -e "    ${Ccom}\tinstall gitsy on specified BINDIR directory or in /usr/bin directory"
         echo -e "    ${Cspe}\tgitsy  ${Copt}install    ${Copt}[ ${Ctext}BINDIR${Copt} ]"
     else
+        echo -e "    ${Ccom}\tuninstall gitsy"
         echo -e "    ${Cspe}\tgitsy  ${Copt}uninstall"
     fi
-        echo -e "    ${Cspe}\tgitsy  ${Copt}help
+        echo -e "    ${Ccom}\tdisplay gitsy version
     ${Cspe}\tgitsy  ${Copt}version
 ${Coff}
 "
 }
 # -------------------------------------------------------
 function gitsy.main(){
-    if [ "$GITSY_HOOKNAME" = "-v" ]; then
+    if [ "$GITSY_COMMAND" = "-v" ]; then
         echo $GITSY_VERSION
         exit
     fi
-    if [ "$GITSY_HOOKNAME" = "-h" ]; then
-        GITSY_HOOKNAME="help"
+    if [ "$GITSY_COMMAND" = "-h" ] || [ "$GITSY_COMMAND" = "--help" ]; then
+        GITSY_COMMAND="help"
     fi
-    GITSY_HOOK="gitsy.${GITSY_HOOKNAME//-/.}"
+    GITSY_CALL="gitsy.${GITSY_COMMAND//-/.}"
     gitsy.title "${GITSY_SCRIPT##*/}" "$GITSY_VERSION"
     gitsy.check.command
-    if [ ! -z "$GITSY_HOOKNAME" ]; then
-        type $GITSY_HOOK > /dev/null 2>&1
+    if [ ! -z "$GITSY_COMMAND" ]; then
         discmd="false"
-        if [ "$GITSY_HOOKNAME" = "install" ] && [ "$GITSY_INSTALLED" = "true" ]; then
+        if [ "$GITSY_COMMAND" = "install" ] && [ "$GITSY_INSTALLED" = "true" ]; then
             discmd="true"
         fi
+        type $GITSY_CALL > /dev/null 2>&1
         if [ $? -eq 0 ] && [ "$discmd" = "false" ]; then
-            #~ echo -e " ${Cspe}command ${Copt}$GITSY_HOOKNAME ${Ctext}$GITSY_PARAMS${Coff}\n"
-            $GITSY_HOOK $GITSY_PARAMS
+            #~ echo -e " ${Cspe}command ${Copt}$GITSY_COMMAND ${Ctext}$GITSY_PARAMS${Coff} $GITSY_CALL\n"
+            $GITSY_CALL $GITSY_PARAMS
             echo
         else
-            gitsy.error "\n
-            invalid command ${Cspe}$GITSY_HOOKNAME${Coff}"
+            gitsy.error "invalid command ${Cspe}$GITSY_COMMAND${Coff}"
         fi
     else
-        gitsy.error "\n
-            you must specified a command !"
+        gitsy.error "you must specified a command !"
     fi
 }
 # -------------------------------------------------------
